version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "monthly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "monthly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "monthly"
      day: "sunday"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "monthly"
      day: "sunday"
