services:
  browser:
    image: browser
    shm_size: "2gb"
    container_name: browser
    cap_add:
      - "SYS_ADMIN"
    command: xvfb-run --auto-servernum --server-args='-screen 0, 1920x1080x24' node dist/script.js
    depends_on:
      - emulator
    volumes:
      - browser-data:/home/pptruser/data
    init: true
    environment:
      - LANGUAGE=env
  emulator:
    image: emulator
    container_name: emulator
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001
    volumes:
      - emulator-config:/config
      - emulator-data:/data
      - ./roms/red.gb:/data/roms/red.gb
volumes:
  emulator-config:
  emulator-data:
  browser-data:
