services:
  browser:
    image: ghcr.io/shepherdjerred/discord-plays-pokemon
    shm_size: "4gb"
    container_name: browser
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - server
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - browser-downloads:/home/user/Downloads
    environment:
      SIZEW: 1920
      SIZEH: 1080
      REFRESH: 60
      PASSWD: password
      BASIC_AUTH_PASSWORD: password
    ports:
      - 8080:8080
  server:
    image: caddy
    container_name: server
    volumes:
      - ./static/:/usr/share/caddy/
      - caddy-data:/data
    ports:
      - 8081:80
volumes:
  browser-downloads:
  caddy-data:
