services:
  browser:
    image: browser
    shm_size: "4gb"
    container_name: browser
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - emulator
    privileged: true
    cap_add:
    - SYS_ADMIN
    volumes:
      - browser-data:/home/user/data
    environment:
      SIZEW: 1920
      SIZEH: 1080
      REFRESH: 60
      PASSWD: password
      BASIC_AUTH_PASSWORD: password
    ports:
      - 8080:8080
  emulator:
    image: lscr.io/linuxserver/emulatorjs
    container_name: emulator
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001
    volumes:
      - emulator-config:/config
      - emulator-data:/data
volumes:
  emulator-config:
  emulator-data:
  browser-data:
