services:
  browser:
    image: browser
    shm_size: "4gb"
    container_name: browser
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    cap_add:
      - "SYS_ADMIN"
    depends_on:
      - emulator
    volumes:
      - browser-data:/home/pptruser/data
    init: true
    ports:
      - 5900:5900
  emulator:
    image: lscr.io/linuxserver/emulatorjs
    container_name: emulator
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001
    volumes:
      - emulator-config:/config
      - emulator-data:/data
volumes:
  emulator-config:
  emulator-data:
  browser-data:
