services:
  browser:
    image: ghcr.io/shepherdjerred/discord-plays-pokemon
    shm_size: "4gb"
    container_name: browser
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - saves:/home/user/Downloads
      - ./.env:/home/user/.env
    environment:
      SIZEW: 1920
      SIZEH: 1080
      REFRESH: 60
      PASSWD: password
      BASIC_AUTH_PASSWORD: password
    ports:
      - 8080:8080
volumes:
  saves:
