VERSION 0.7
PROJECT sjerred/discord-plays-pokemon

insiders:
  FROM ubuntu:jammy
  WORKDIR /workspace
  RUN apt update
  RUN apt install -y zip
  GIT CLONE --branch 9.2.7-insiders-4.40.3 https://github.com/squidfunk/mkdocs-material-insiders .
  RUN zip -r insiders.zip .
  SAVE ARTIFACT insiders.zip

pipenv:
  FROM python:3.11
  WORKDIR /workspace
  RUN pip install --upgrade pip
  RUN pip install pipenv
  # https://pipenv-fork.readthedocs.io/en/latest/advanced.html#changing-pipenv-s-cache-location
  ENV PIPENV_CACHE_DIR=/pipenv_cache
  CACHE $PIPENV_CACHE_DIR

deps:
  FROM +pipenv
  RUN apt update -y
  # https://squidfunk.github.io/mkdocs-material/setup/dependencies/image-processing/#linux
  RUN apt install -y pngquant libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
  WORKDIR docs
  COPY Pipfile* .
  COPY +insiders/insiders.zip .
  RUN pipenv install --deploy --system

lock:
  FROM +pipenv
  COPY Pipfile* .
  COPY +insiders/insiders.zip .
  RUN pipenv lock
  SAVE ARTIFACT Pipfile.lock AS LOCAL Pipfile.lock

src:
  FROM +deps
  COPY docs docs
  COPY overrides overrides
  COPY mkdocs.yml .

build:
  FROM +src
  CACHE .cache
  RUN pipenv run mkdocs build
  SAVE ARTIFACT site/* AS LOCAL site/

image:
  FROM +src
  SAVE IMAGE discord-plays-pokemon:docs

dev:
  LOCALLY
  WITH DOCKER --load=+image
    # Open a web browser once mkdocs is ready
    RUN (curl --output /dev/null --silent --retry 30 --retry-delay 1 --retry-all-errors \
        http://localhost:8080 && \
        python3 -m webbrowser http://localhost:8080) & \
      docker run \
        --rm \
        -p 8080:8080 \
        -v $(pwd)/docs:/workspace/docs/docs \
        -v $(pwd)/mkdocs.yml:/workspace/docs/mkdocs.yml \
        discord-plays-pokemon:docs \
        pipenv run mkdocs serve -a 0.0.0.0:8080
  END

deploy:
  ARG prod=false
  FROM node:lts
  ENV NETLIFY_SITE_ID=74b8286f-3e2f-4b8e-87bf-d9043c307c33
  RUN npm i -g netlify-cli
  COPY +build/ site
  RUN --push --no-cache --secret NETLIFY_AUTH_TOKEN=netlify_token npx netlify-cli link
  IF [ $prod = "true" ]
    RUN --push --no-cache --secret NETLIFY_AUTH_TOKEN=netlify_token npx netlify-cli deploy --dir=site --prod
  ELSE
    RUN --push --no-cache --secret NETLIFY_AUTH_TOKEN=netlify_token npx netlify-cli deploy --dir=site
  END
