site_name: Discord Plays Pokémon
site_url: https://docs.discord-plays-pokemon.com/
repo_url: https://github.com/shepherdjerred/discord-plays-pokemon
edit_uri: edit/main/docs/docs/
nav:
  - Home: index.md
  - Guide:
      - user/index.md
      - user/web.md
      - user/aws.md
      - user/docker.md
  - Development:
      - development/index.md
      - development/architecture.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/pokeball.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Nunito
    code: Fira Code
  favicon: assets/images/pokeball.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: red
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.path
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.tooltips
    - navigation.footer
    - announce.dismiss
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - toc:
      permalink: true
plugins:
  - privacy:
      links_attr_map:
        target: _blank
  - search
  - social
  - optimize
  - offline
  - typeset

extra_css:
  - assets/css/links.css
